Repository FakerPHP/Faker, pull requests merged in 2020-12, with the labels that each got.

#89 Add UK National Insurance number generator
  src/Faker/Provider/en_GB/Person.php
  test/Faker/Provider/en_GB/PersonTest.php
Labels: enhancement

#98 Fix en_GB national insurance number test
  src/Faker/Provider/en_GB/Person.php
  test/Faker/Provider/en_GB/PersonTest.php
Labels: bug

#96 Refactor of CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#87 Remove usage of mt_rand
  src/Faker/ORM/CakePHP/ColumnTypeGuesser.php
  src/Faker/ORM/Doctrine/ColumnTypeGuesser.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Mandango/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel2/ColumnTypeGuesser.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Spot/ColumnTypeGuesser.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/Provider/Barcode.php
  src/Faker/Provider/Color.php
  src/Faker/Provider/DateTime.php
  src/Faker/Provider/HtmlLorem.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/Lorem.php
  src/Faker/Provider/Miscellaneous.php
  src/Faker/Provider/Payment.php
  src/Faker/Provider/UserAgent.php
  src/Faker/Provider/Uuid.php
  src/Faker/Provider/bn_BD/Address.php
  src/Faker/Provider/cs_CZ/Person.php
  src/Faker/Provider/da_DK/Person.php
  src/Faker/Provider/en_US/Company.php
  src/Faker/Provider/en_US/Person.php
  src/Faker/Provider/id_ID/Address.php
  src/Faker/Provider/is_IS/Person.php
  src/Faker/Provider/it_IT/Company.php
  src/Faker/Provider/ja_JP/Address.php
  src/Faker/Provider/kk_KZ/Company.php
  src/Faker/Provider/kk_KZ/Person.php
  src/Faker/Provider/ms_MY/Address.php
  src/Faker/Provider/ms_MY/Miscellaneous.php
  src/Faker/Provider/ms_MY/Person.php
  src/Faker/Provider/nl_NL/Company.php
  src/Faker/Provider/nl_NL/Person.php
  src/Faker/Provider/pl_PL/Company.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/Provider/ru_RU/Company.php
  src/Faker/Provider/th_TH/Person.php
  src/Faker/Provider/uk_UA/Address.php
  src/Faker/Provider/zh_CN/Address.php
  src/Faker/Provider/zh_TW/Address.php
  src/Faker/Provider/zh_TW/Person.php
Labels: enhancement, invalid

#127 Fix: Remove trailing space
  .github/workflows/continuous-integration.yml
Labels: bug

#128 Enhancement: Link LICENSE file
  README.md
Labels: enhancement

#129 Enhancement: Update phpstan/phpstan
  vendor-bin/phpstan/composer.json
Labels: enhancement

#130 Enhancement: Update psalm/phar
  vendor-bin/psalm/composer.json
Labels: enhancement

#131 Enhancement: Add configuration for Dependabot
  .github/dependabot.yml
Labels: enhancement

#137 Enhancement: Check in composer.lock for development tools
  .github/workflows/static-analysis.yml
  .gitignore
  Makefile
  vendor-bin/phpstan/composer.lock
  vendor-bin/psalm/composer.lock
Labels: enhancement

#138 Fix: Configure platform for development tools
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: bug

#139 Fix: Require vimeo/psalm instead of psalm/phar
  .github/workflows/static-analysis.yml
  Makefile
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: bug

#140 Fix: Avoid exact version constraints
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: bug

#159 Fix: Do not create directory that is not needed
  Makefile
Labels: bug

#160 Fix: Configure concat_space fixer to concatenate strings without space
  .php_cs.dist
Labels: bug

#172 Fix: Adjust Makefile to account for use of symfony/phpunit-bridge
  Makefile
Labels: bug

#173 Fix: Let build target be the first target
  Makefile
Labels: bug

#174 Fix: Run static code analysis before running tests
  Makefile
Labels: bug

#177 Fix: Move installation of phpunit/phpunit to different step
  .github/workflows/tests.yml
Labels: bug

#179 Fix: Keep attributes sorted by name
  phpunit.xml.dist
Labels: bug

#180 Fix: Disable code coverage drivers when running tests
  .github/workflows/tests.yml
Labels: bug

#178 Enhancement: Collect and send code coverage to codecov.io
  .gitattributes
  .github/workflows/code-coverage.yml
  README.md
  codecov.yml
Labels: enhancement

#181 Enhancement: Enable and configure class_attributes_separation fixer
  .php_cs.dist
  src/Faker/ORM/Spot/ColumnTypeGuesser.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/cs_CZ/Person.php
  src/Faker/Provider/es_PE/Person.php
  src/Faker/Provider/fa_IR/PhoneNumber.php
  src/Faker/Provider/fr_FR/PhoneNumber.php
  src/Faker/Provider/ka_GE/Address.php
  src/Faker/Provider/ka_GE/Company.php
  src/Faker/Provider/ko_KR/PhoneNumber.php
  src/Faker/Provider/nl_NL/Company.php
  src/Faker/Provider/pt_BR/Payment.php
  test/Faker/Calculator/IbanTest.php
  test/Faker/Provider/BaseTest.php
  test/Faker/Provider/PaymentTest.php
  test/Faker/Provider/ProviderOverrideTest.php
  test/Faker/Provider/fr_FR/CompanyTest.php
  test/Faker/Provider/ja_JP/PhoneNumberTest.php
  test/Faker/Provider/kk_KZ/CompanyTest.php
  test/Faker/Provider/kk_KZ/PersonTest.php
  test/Faker/Provider/mn_MN/PersonTest.php
  test/Faker/Provider/pt_PT/PhoneNumberTest.php
  test/Faker/Provider/ro_RO/PersonTest.php
Labels: enhancement

#184 Fix: Run 'make baseline'
  phpstan-baseline.neon
  psalm.baseline.xml
Labels: bug

#182 Enhancement: Enable and configure phpdoc_types_order fixer
  .php_cs.dist
  psalm.baseline.xml
  src/Faker/Generator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/DateTime.php
  src/Faker/Provider/id_ID/Person.php
  src/Faker/Provider/ms_MY/Address.php
  src/Faker/Provider/pt_BR/check_digit.php
  src/Faker/Provider/ro_RO/Person.php
Labels: enhancement

#191 Fix: Order
  psalm.xml
Labels: bug

#188 Fix: Do not configure deprecated php_unit_ordered_covers fixer
  .php_cs.dist
Labels: bug

#190 Enhancement: Enable return_assignment fixer
  .php_cs.dist
  src/Faker/Provider/fr_FR/PhoneNumber.php
Labels: enhancement

#189 Enhancement: Enable no_useless_else fixer
  .php_cs.dist
  src/Faker/Provider/ms_MY/PhoneNumber.php
Labels: enhancement

#187 Enhancement: Enable no_extra_blank_lines fixer
  .php_cs.dist
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/Provider/el_GR/Company.php
  src/Faker/Provider/en_HK/Address.php
  src/Faker/Provider/hr_HR/Address.php
  src/Faker/Provider/nb_NO/Address.php
  src/Faker/Provider/nb_NO/Person.php
  src/Faker/Provider/sv_SE/Person.php
  test/Faker/Calculator/IbanTest.php
  test/Faker/Provider/nl_NL/PersonTest.php
Labels: enhancement

#186 Enhancement: Enable increment_style fixer
  .php_cs.dist
  src/Faker/Calculator/Iban.php
  src/Faker/Calculator/Inn.php
  src/Faker/ORM/CakePHP/Populator.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/ORM/Spot/Populator.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/HtmlLorem.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/Lorem.php
  src/Faker/Provider/Text.php
  src/Faker/Provider/en_SG/Person.php
  src/Faker/Provider/fa_IR/Person.php
  src/Faker/Provider/is_IS/Person.php
  src/Faker/Provider/kk_KZ/Person.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/nl_NL/Person.php
  src/Faker/Provider/pl_PL/Company.php
  src/Faker/Provider/pl_PL/Payment.php
  src/Faker/Provider/pl_PL/Person.php
  src/Faker/Provider/pt_BR/check_digit.php
  src/Faker/Provider/pt_PT/Person.php
  src/Faker/UniqueGenerator.php
  src/Faker/ValidGenerator.php
  test/Faker/Calculator/IbanTest.php
  test/Faker/Provider/BaseTest.php
  test/Faker/Provider/BiasedTest.php
  test/Faker/Provider/cs_CZ/PersonTest.php
  test/Faker/Provider/de_AT/PersonTest.php
  test/Faker/Provider/en_US/PersonTest.php
  test/Faker/Provider/en_US/PhoneNumberTest.php
  test/Faker/Provider/en_ZA/PhoneNumberTest.php
  test/Faker/Provider/fa_IR/PersonTest.php
  test/Faker/Provider/fi_FI/PersonTest.php
  test/Faker/Provider/ja_JP/PhoneNumberTest.php
  test/Faker/Provider/nb_NO/PhoneNumberTest.php
  test/Faker/Provider/nl_NL/PersonTest.php
  test/Faker/Provider/pl_PL/LicensePlateTest.php
  test/Faker/Provider/tr_TR/PersonTest.php
  test/Faker/Provider/tr_TR/PhoneNumberTest.php
  test/test.php
Labels: enhancement

#185 Enhancement: Enable unary_operator_spaces fixer
  .php_cs.dist
  src/Faker/Provider/is_IS/Person.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/zh_TW/Text.php
Labels: enhancement

#195 Enhancement: Enable no_superfluous_elseif fixer
  .php_cs.dist
  src/Faker/Provider/Person.php
  src/Faker/Provider/bg_BG/Person.php
  src/Faker/Provider/cs_CZ/Company.php
  src/Faker/Provider/cs_CZ/Person.php
  src/Faker/Provider/el_GR/Person.php
  src/Faker/Provider/ja_JP/Person.php
  src/Faker/Provider/kk_KZ/Person.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/pl_PL/Person.php
  src/Faker/Provider/ru_RU/Person.php
  src/Faker/Provider/sk_SK/Person.php
  src/Faker/Provider/uk_UA/Person.php
  src/Faker/Provider/vi_VN/Person.php
Labels: enhancement

#196 Enhancement: Configure blank_line_before_statement fixer to add blank line before if statement
  .php_cs.dist
  src/Faker/Calculator/Luhn.php
  src/Faker/Documentor.php
  src/Faker/Factory.php
  src/Faker/Guesser/Name.php
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/ORM/CakePHP/Populator.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/ColumnTypeGuesser.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/ORM/Spot/Populator.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/HtmlLorem.php
  src/Faker/Provider/Image.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/Lorem.php
  src/Faker/Provider/Payment.php
  src/Faker/Provider/Text.php
  src/Faker/Provider/UserAgent.php
  src/Faker/Provider/cs_CZ/Company.php
  src/Faker/Provider/cs_CZ/Person.php
  src/Faker/Provider/en_UG/Person.php
  src/Faker/Provider/es_VE/Person.php
  src/Faker/Provider/fi_FI/Person.php
  src/Faker/Provider/fr_FR/Company.php
  src/Faker/Provider/fr_FR/Payment.php
  src/Faker/Provider/id_ID/Person.php
  src/Faker/Provider/nl_BE/Person.php
  src/Faker/Provider/nl_NL/Person.php
  src/Faker/Provider/pl_PL/Company.php
  src/Faker/Provider/pl_PL/Person.php
  src/Faker/Provider/pt_BR/check_digit.php
  src/Faker/Provider/pt_PT/Person.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/UniqueGenerator.php
  src/Faker/ValidGenerator.php
  src/autoload.php
  test/Faker/Provider/DateTimeTest.php
  test/Faker/Provider/ImageTest.php
  test/Faker/Provider/cs_CZ/PersonTest.php
  test/Faker/Provider/es_ES/PaymentTest.php
  test/Faker/Provider/fr_FR/PaymentTest.php
  test/Faker/Provider/pt_PT/PersonTest.php
Labels: enhancement

#194 Enhancement: Enable trim_array_spaces fixer
  .php_cs.dist
  src/Faker/Provider/en_UG/Address.php
  src/Faker/Provider/es_PE/Address.php
  src/Faker/Provider/lt_LT/Person.php
Labels: enhancement

#197 Fix: Run 'make cs'
  src/Faker/Provider/Person.php
  src/Faker/Provider/bg_BG/Person.php
  src/Faker/Provider/cs_CZ/Company.php
  src/Faker/Provider/cs_CZ/Person.php
  src/Faker/Provider/el_GR/Person.php
  src/Faker/Provider/ja_JP/Person.php
  src/Faker/Provider/kk_KZ/Person.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/pl_PL/Person.php
  src/Faker/Provider/ru_RU/Person.php
  src/Faker/Provider/sk_SK/Person.php
  src/Faker/Provider/uk_UA/Person.php
  src/Faker/Provider/vi_VN/Person.php
Labels: bug

#193 Enhancement: Enable is_null fixer
  .php_cs.dist
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/Provider/Image.php
  src/Faker/Provider/Payment.php
  src/Faker/Provider/ms_MY/Address.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/ValidGenerator.php
  test/Faker/Provider/pt_PT/PersonTest.php
Labels: enhancement

#200 Fix: Command is not a dependency
  Makefile
Labels: bug

#199 Enhancement: Enable no_superfluous_phpdoc_tags fixer
  .php_cs.dist
  phpstan-baseline.neon
  psalm.baseline.xml
  src/Faker/Calculator/Isbn.php
  src/Faker/DefaultGenerator.php
  src/Faker/Documentor.php
  src/Faker/Generator.php
  src/Faker/Guesser/Name.php
  src/Faker/ORM/CakePHP/Populator.php
  src/Faker/ORM/Doctrine/ColumnTypeGuesser.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Mandango/ColumnTypeGuesser.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/ColumnTypeGuesser.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/ORM/Spot/ColumnTypeGuesser.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/ORM/Spot/Populator.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/DateTime.php
  src/Faker/Provider/de_AT/Person.php
  src/Faker/Provider/hy_AM/PhoneNumber.php
  src/Faker/Provider/pl_PL/LicensePlate.php
  src/Faker/Provider/pt_BR/PhoneNumber.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/UniqueGenerator.php
  src/Faker/ValidGenerator.php
Labels: enhancement

#208 class_exists consistently called with ::class
  src/Faker/Provider/Internet.php
  test/Faker/Provider/ProviderOverrideTest.php
Labels: enhancement

#203 Enhancement: Enable phpdoc_line_span fixer
  .php_cs.dist
  src/Faker/Calculator/Ean.php
  src/Faker/Calculator/Isbn.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/Provider/Image.php
  src/Faker/Provider/pt_PT/Address.php
  src/Faker/Provider/pt_PT/Person.php
Labels: enhancement

#201 Enhancement: Configure cache directory for phpstan/phpstan and vimeo/psalm
  phpstan.neon.dist
  psalm.xml
Labels: enhancement

#202 Enhancement: Enable multiline_comment_opening_closing fixer
  .php_cs.dist
  src/Faker/Provider/ar_SA/Color.php
  src/Faker/Provider/ar_SA/Company.php
  src/Faker/Provider/de_AT/Person.php
  src/Faker/Provider/de_DE/Person.php
  src/Faker/Provider/he_IL/Address.php
  src/Faker/Provider/he_IL/Person.php
  src/Faker/Provider/id_ID/Address.php
  src/Faker/Provider/id_ID/Color.php
  src/Faker/Provider/is_IS/Address.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/lv_LV/Person.php
  src/Faker/Provider/lv_LV/PhoneNumber.php
  src/Faker/Provider/ru_RU/Person.php
  src/Faker/Provider/sl_SI/Address.php
Labels: enhancement

#205 Enhancement: Enable phpdoc_no_empty_return fixer
  .php_cs.dist
  src/Faker/Provider/DateTime.php
Labels: enhancement

#120 Add used extensions to composer.json
  composer.json
  src/Faker/Provider/HtmlLorem.php
Labels: bug

#209 Enhancement: Enable phpdoc_trim_consecutive_blank_line_separation fixer
  .php_cs.dist
  src/Faker/Provider/fr_CA/Text.php
Labels: enhancement

#211 Enhancement: Enable semicolon_after_instruction fixer
  .php_cs.dist
  test/documentor.php
  test/test.php
Labels: enhancement

#210 Enhancement: Enable static_lambda fixer
  .php_cs.dist
  src/Faker/Calculator/Isbn.php
  src/Faker/Guesser/Name.php
  src/Faker/ORM/CakePHP/ColumnTypeGuesser.php
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/ORM/Doctrine/ColumnTypeGuesser.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Mandango/ColumnTypeGuesser.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel2/ColumnTypeGuesser.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Spot/ColumnTypeGuesser.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/File.php
  src/Faker/ValidGenerator.php
  test/Faker/Provider/BaseTest.php
Labels: enhancement

#108 Move TCNo and INN from calculator to localized providers
  src/Faker/Calculator/Inn.php
  src/Faker/Calculator/TCNo.php
  src/Faker/Provider/ru_RU/Company.php
  src/Faker/Provider/tr_TR/Person.php
  test/Faker/Calculator/InnTest.php
  test/Faker/Calculator/TCNoTest.php
  test/Faker/Provider/ru_RU/CompanyTest.php
  test/Faker/Provider/tr_TR/PersonTest.php
Labels: enhancement

#206 Fix regex dot/backslash issue
  src/Faker/Provider/Base.php
  test/Faker/Provider/BaseTest.php
Labels: bug

#215 Enhancement: Enable no_spaces_around_offset fixer
  .php_cs.dist
  src/Faker/Documentor.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/Lorem.php
Labels: enhancement

#212 Enhancement: Enable no_blank_lines_after_phpdoc fixer
  .php_cs.dist
  src/Faker/Provider/en_CA/Address.php
  src/Faker/Provider/id_ID/Color.php
  src/Faker/Provider/ko_KR/Person.php
  src/Faker/Provider/pt_PT/Person.php
Labels: enhancement

#217 Enhancement: Enable no_unneeded_control_parentheses fixer
  .php_cs.dist
  src/Faker/Provider/DateTime.php
Labels: enhancement

#213 Enhancement: Enable and configure operator_linebreak fixer
  .php_cs.dist
  src/Faker/ORM/Mandango/EntityPopulator.php
  test/Faker/Provider/es_ES/PaymentTest.php
  test/Faker/Provider/es_ES/PersonTest.php
Labels: enhancement

#218 Enhancement: Enable no_whitespace_before_comma_in_array fixer
  .php_cs.dist
  src/Faker/Provider/lv_LV/Address.php
  src/Faker/Provider/pt_PT/Person.php
Labels: enhancement

#154 Adding support for extensions and PSR-11
  composer.json
  phpstan-baseline.neon
  psalm.baseline.xml
  src/Faker/Core/File.php
  src/Faker/Extension/Container.php
  src/Faker/Extension/ContainerBuilder.php
  src/Faker/Extension/ContainerException.php
  src/Faker/Extension/Extension.php
  src/Faker/Extension/ExtensionNotFound.php
  src/Faker/Extension/FileExtension.php
  src/Faker/Extension/GeneratorAwareExtension.php
  src/Faker/Extension/NotInContainerException.php
  src/Faker/Generator.php
  test/Faker/Extension/ContainerBuilderTest.php
  test/Faker/Extension/ContainerTest.php
  test/Faker/GeneratorTest.php
Labels: enhancement

#214 Enhancement: Enable no_trailing_comma_in_singleline_array fixer
  .php_cs.dist
  src/Faker/Provider/ar_JO/Address.php
Labels: enhancement

#222 Enhancement: Enable phpdoc_no_access fixer
  .php_cs.dist
  src/Faker/Provider/en_IN/Person.php
  src/Faker/Provider/id_ID/Person.php
  src/Faker/Provider/ru_RU/Person.php
  src/Faker/Provider/uk_UA/Person.php
Labels: enhancement

#219 Enhancement: Enable binary_operator_spaces fixer
  .php_cs.dist
  src/Faker/Core/File.php
  src/Faker/Documentor.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/DateTime.php
  src/Faker/Provider/File.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/Lorem.php
  src/Faker/Provider/Payment.php
  src/Faker/Provider/cs_CZ/DateTime.php
  src/Faker/Provider/fr_FR/PhoneNumber.php
  src/Faker/Provider/kk_KZ/Company.php
  src/Faker/Provider/kk_KZ/Person.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/nl_NL/Person.php
  src/Faker/Provider/pt_BR/PhoneNumber.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/Provider/ru_RU/Company.php
  src/Faker/Provider/th_TH/Address.php
  src/Faker/UniqueGenerator.php
  test/Faker/Provider/BaseTest.php
  test/Faker/Provider/fi_FI/PersonTest.php
  test/Faker/Provider/kk_KZ/CompanyTest.php
  test/Faker/Provider/kk_KZ/PersonTest.php
  test/Faker/Provider/pl_PL/PersonTest.php
  test/test.php
Labels: enhancement

#220 Enhancement: Enable and configure list_syntax fixer
  .php_cs.dist
  src/Faker/Provider/Payment.php
  test/Faker/Provider/ImageTest.php
Labels: enhancement

#165 Adding trait for GeneratorAwareExtension
  src/Faker/Extension/GeneratorAwareExtensionTrait.php
  test/Faker/Extension/GeneratorAwareExtensionTest.php
Labels: enhancement

#225 Enhancement: Keep packages sorted in composer.json
  vendor-bin/php-cs-fixer/composer.json
  vendor-bin/phpstan/composer.json
  vendor-bin/psalm/composer.json
Labels: enhancement

#226 Enhancement: Require phpstan/extension-installer
  vendor-bin/phpstan/composer.json
  vendor-bin/phpstan/composer.lock
Labels: dependency, enhancement

#162 Added helper class for extension
  src/Faker/Extension/Helper.php
  test/Faker/Extension/HelperTest.php
Labels: enhancement

#227 Fix: Let phpstan report unmatched ignored errors
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: bug

#230 Enhancement: Configure braces fixer to allow empty single-line anonymous classes
  .php_cs.dist
Labels: enhancement

#229 Fix: Force execution of vendor target
  Makefile
Labels: bug

#228 Fix: Add missing tests for ContainerBuilder
  test/Faker/Extension/ContainerBuilderTest.php
Labels: bug

#231 Enhancement: Enable comments from codecov.io
  .gitattributes
  codecov.yml
Labels: enhancement

#207 Enhancement: Enable strict_param fixer
  .php_cs.dist
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/Provider/en_GB/Person.php
  src/Faker/Provider/en_ZA/PhoneNumber.php
  src/Faker/Provider/ja_JP/Text.php
  src/Faker/Provider/ms_MY/Person.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/Provider/zh_TW/Text.php
  test/Faker/Provider/en_SG/PersonTest.php
  test/Faker/Provider/ro_RO/PersonTest.php
Labels: enhancement

#216 Enhancement: Enable and configure global_namespace_import fixer
  .php_cs.dist
  psalm.baseline.xml
  src/Faker/Calculator/Luhn.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/Provider/tr_TR/Person.php
  test/Faker/Calculator/IsbnTest.php
  test/Faker/Provider/pl_PL/PersonTest.php
Labels: enhancement

#236 Enhancement: Enable single_line_comment_style fixer
  .php_cs.dist
  phpstan-baseline.neon
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/Provider/hu_HU/Address.php
  src/Faker/Provider/hu_HU/Person.php
  src/Faker/Provider/id_ID/Person.php
Labels: enhancement

#237 Fix: Let dependabot update dependencies in vendor-bin/php-cs-fixer
  .github/dependabot.yml
Labels: bug

#239 Enhancement: Enable and configure phpdoc_order_by_value fixer
  .php_cs.dist
  src/Faker/Extension/Container.php
  src/Faker/Generator.php
Labels: enhancement

#233 Fix: Add test to assert unique() behaviour
  test/Faker/GeneratorTest.php
Labels: bug

#232 Added medical extension to core
  src/Faker/Core/Blood.php
  src/Faker/Extension/BloodExtension.php
  src/Faker/Extension/ContainerBuilder.php
  src/Faker/Generator.php
  test/Faker/Core/BloodTest.php
Labels: enhancement
