Repository FakerPHP/Faker, pull requests merged in 2020-10, with the labels that each got.

#5 Updates the Danish addresses
  src/Faker/Provider/da_DK/Address.php
Labels: bug, enhancement

#6 Fix: Case
  README.md
Labels: bug

#8 Fix: Remove conflict with ergebnis/faker
  composer.json
Labels: bug

#7 Fix: Move CONTRIBUTING.md into .github/
  .gitattributes
  .github/CONTRIBUTING.md
Labels: bug

#12 Remove two inappropriate Dutch job titles
  src/Faker/Provider/nl_NL/Company.php
Labels: bug

#11 Standin replacement for LoremPixel to Placeholder.com
  src/Faker/Provider/Image.php
  test/Faker/Provider/ImageTest.php
Labels: bug, help wanted

#14 Adding BC check
  .gitattributes
  .github/workflows/bc-check.yml
  roave-bc-check.yaml
Labels: enhancement

#28 Add PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#9 Adding PHPStan and Psalm
  .gitattributes
  .github/workflows/static-analysis.yml
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.baseline.xml
  psalm.xml
Labels: enhancement

#31 Update branch alias automatically after tag
  .github/workflows/branch-alias.yml
Labels: enhancement

#35 Other Brazilian names
  src/Faker/Provider/pt_BR/Person.php
Labels: enhancement
