Repository FakerPHP/Faker, pull requests merged in 2021-01, with the labels that each got.

#248 Shorten the stale period to 14 days instead of the original 30
  .github/stale.yml
Labels: enhancement

#245 [Core] Improve checks in blood tests
  test/Faker/Core/BloodTest.php
Labels: enhancement

#244 [es_PE] Add RUC
  src/Faker/Provider/es_PE/Company.php
  test/Faker/Provider/es_PE/CompanyTest.php
Labels: enhancement

#252 Added barcode extension to core
  src/Faker/Core/Barcode.php
  src/Faker/Extension/BarcodeExtension.php
  src/Faker/Extension/ContainerBuilder.php
  src/Faker/Generator.php
  test/Faker/Core/BarcodeTest.php
Labels: enhancement

#255 [en_GB] VAT number faker
  src/Faker/Provider/en_GB/Company.php
  test/Faker/Provider/en_GB/CompanyTest.php
Labels: enhancement

#258 Added new districts for the country nepal
  src/Faker/Provider/ne_NP/Address.php
Labels: enhancement

#261 Fix U.S. Area Code Generation
  src/Faker/Provider/en_US/PhoneNumber.php
Labels: bug

#257 [Core] Added number extension
  src/Faker/Core/Number.php
  src/Faker/Extension/ContainerBuilder.php
  src/Faker/Extension/NumberExtension.php
  src/Faker/Generator.php
  test/Faker/Core/NumberTest.php
Labels: enhancement

#256 [Core] Fix Helper::numerify
  src/Faker/Extension/Helper.php
  test/Faker/Extension/HelperTest.php
Labels: bug

#234 Extract fixtures into separate classes
  composer.json
  test/Faker/GeneratorTest.php
  test/Fixture/Provider/BarProvider.php
  test/Fixture/Provider/FooProvider.php
Labels: enhancement, pinned
