Repository FakerPHP/Faker, pull requests merged in 2022-12, with the labels that each got.

#560 Fix: Remove platform configuration
  composer.json
Labels: bug

#559 Fix: Command for generating the baseline for `vimeo/psalm`
  Makefile
Labels: bug

#528 Ensure php 8.2 compatibility
  .github/workflows/tests.yml
  CHANGELOG.md
  phpunit.xml.dist
Labels: enhancement, pinned

#491 Add Swedish `mobileNumber()`
  src/Faker/Provider/sv_SE/PhoneNumber.php
  test/Faker/Provider/sv_SE/PhoneNumberTest.php
Labels: enhancement, pinned

#570 Fix PHP 8.2 warning: Use `[static::class, '…']` instead of `'static::…` for callbacks
  phpstan-baseline.neon
  phpunit.xml.dist
  psalm.baseline.xml
  src/Faker/Provider/Base.php
  src/Faker/Provider/en_CA/Address.php
Labels: bug

#572 Fix bc check
  .github/workflows/bc-check.yaml
  .php-cs-fixer.dist.php
  src/Faker/Generator.php
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/ORM/Spot/Populator.php
  src/Faker/Provider/DateTime.php
Labels: bug

#542 Enhancement: Add rector config file for easy migration
  .github/dependabot.yml
  .github/workflows/rector.yaml
  .gitignore
  Makefile
  README.md
  rector-migrate.php
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
Labels: enhancement

#577 Remove invalid config reference in `README.md`
  README.md
Labels: bug

#579 Remove concept of OS from rector workflow
  .github/workflows/rector.yaml
Labels: bug
