Repository FakerPHP/Faker, pull requests merged in 2023-05, with the labels that each got.

#639 Fix: Clean up `randomElements()` and `randomElement()`
  phpstan-baseline.neon
  psalm.baseline.xml
  src/Faker/Provider/Base.php
Labels: bug

#638 Fix: Do not configure deprecated `braces` fixer
  .php-cs-fixer.dist.php
Labels: bug

#620 allows passing an `enum` to `randomElement()` or `randomElements()`
  .php-cs-fixer.dist.php
  phpstan-baseline.neon
  psalm.baseline.xml
  src/Faker/Provider/Base.php
  test/Faker/Provider/BaseTest.php
  test/Fixture/Enum/BackedEnum.php
Labels: enhancement

#628 Fix: Update `CHANGELOG.md`
  CHANGELOG.md
Labels: pinned
