Repository FakerPHP/Faker, pull requests merged in 2023-09, with the labels that each got.

#693 Fix: Allow tests to fail on PHP 8.3
  .github/workflows/tests.yaml
Labels: bug

#695 Fix: Test does not perform any assertions
  test/Faker/UniqueGeneratorTest.php
Labels: bug

#696 Fix: Operator
  test/Faker/Provider/ImageTest.php
Labels: bug

#697 Fix: Use boolean expressions
  src/Faker/Core/Version.php
  src/Faker/Extension/Helper.php
  src/Faker/Provider/Base.php
Labels: bug

#702 Fix: Require to pass name to `ContainerBuilder::add()`
  roave-bc-check.yaml
  src/Faker/Container/ContainerBuilder.php
  test/Faker/Extension/ContainerBuilderTest.php
  test/Faker/GeneratorTest.php
Labels: bug

#701 Enhancement: Run tests in random order
  phpunit.xml.dist
Labels: enhancement

#699 Fix: Add property type declarations
  src/Faker/Container/Container.php
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#698 Fix: Enable and configure `type_declaration_spaces` instead of deprecated `function_typehint_space` fixer
  .php-cs-fixer.dist.php
Labels: bug

#703 Fix: Switch order of parameters
  roave-bc-check.yaml
  src/Faker/Container/ContainerBuilder.php
  test/Faker/Extension/ContainerBuilderTest.php
  test/Faker/GeneratorTest.php
Labels: bug

#711 Fix: Remove unused method
  roave-bc-check.yaml
  src/Faker/Container/Container.php
  src/Faker/Container/ContainerInterface.php
Labels: bug

#710 Fix: Add parameter type declaration
  src/Faker/Container/Container.php
Labels: bug

#712 Fix: Order
  roave-bc-check.yaml
Labels: bug

#715 Enhancement: Reuse `NumberExtension`
  src/Faker/Core/Barcode.php
  src/Faker/Core/Color.php
  src/Faker/Core/Coordinates.php
  src/Faker/Core/Number.php
  src/Faker/Core/Uuid.php
  src/Faker/Core/Version.php
Labels: enhancement

#708 Fix: Methods are instance methods
  src/Faker/Core/Coordinates.php
  src/Faker/Core/Number.php
Labels: bug

#713 Fix: Add property type declarations
  src/Faker/Core/Blood.php
  src/Faker/Core/Color.php
  src/Faker/Core/DateTime.php
  src/Faker/Core/File.php
  src/Faker/Core/Version.php
Labels: bug

#714 Fix: Reduce visibility
  roave-bc-check.yaml
  src/Faker/Core/DateTime.php
Labels: bug

#709 Fix: Do not memoize invalid service
  src/Faker/Container/Container.php
  test/Faker/Extension/ContainerTest.php
Labels: bug

#717 Fix: Consistently describe experimental status
  src/Faker/Core/DateTime.php
Labels: bug

#716 Fix: Mark classes as experimental
  src/Faker/Core/Coordinates.php
  src/Faker/Core/Uuid.php
  src/Faker/Core/Version.php
Labels: bug

#718 Fix: Mark class as `final`
  roave-bc-check.yaml
  src/Faker/Core/Coordinates.php
Labels: bug

#726 Fix: Return string
  phpstan-baseline.neon
  psalm.baseline.xml
  src/Faker/Calculator/Luhn.php
Labels: bug

#722 Fix: Order
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#721 Fix: Avoid unnecessary imports
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#728 Enhancement: Enable `self_static_accessor` fixer
  .php-cs-fixer.dist.php
  src/Faker/Extension/Helper.php
  test/Faker/Provider/ProviderOverrideTest.php
  test/Faker/Provider/id_ID/PersonTest.php
  test/Faker/Provider/ro_RO/PersonTest.php
Labels: enhancement

#729 Fix: Cache for `friendsofphp/php-cs-fixer`
  .github/workflows/coding-standards.yaml
Labels: bug

#727 Fix: Add tests for `Container`
  test/Faker/Extension/ContainerTest.php
  test/Fixture/Container/UnconstructableClass.php
Labels: bug

#720 Fix: Simplify
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#685 updated polish license plates
  src/Faker/Provider/pl_PL/LicensePlate.php
  test/Faker/Provider/pl_PL/LicensePlateTest.php
Labels: enhancement

#734 Fix: Update `CHANGELOG.md`
  CHANGELOG.md
Labels: bug

#730 Fix: Avoid useless tests for `ContainerBuilder`
  test/Faker/Extension/ContainerBuilderTest.php
Labels: bug

#731 Fix: Rename parameter
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#735 Add changelog mention in review checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#732 Enhancement: Allow creating `ContainerBuilder` with definitions for default extensions
  src/Faker/Container/ContainerBuilder.php
  src/Faker/Generator.php
  test/Faker/Extension/ContainerBuilderTest.php
Labels: enhancement

#719 Fix: Reduce visibility
  roave-bc-check.yaml
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#736 Fix: Remove unused method
  roave-bc-check.yaml
  src/Faker/Container/ContainerBuilder.php
Labels: bug

#739 Enhancement: Add `SECURITY.md`
  .github/SECURITY.md
Labels: enhancement

#754 Enhancement: Use `Helper` to select random element instead of `array_rand()`
  src/Faker/Core/File.php
  src/Faker/ORM/CakePHP/EntityPopulator.php
Labels: enhancement

#756 Enhancement: Use `Helper` to determine largest random number
  src/Faker/Core/Number.php
  src/Faker/Extension/Helper.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/Biased.php
Labels: enhancement

#755 Enhancement: Use `Helper` to generate random number without arguments
  src/Faker/Extension/Helper.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/Biased.php
Labels: enhancement

#757 Enhancement: Use `Helper` to select random number between minimum and maximum
  src/Faker/ChanceGenerator.php
  src/Faker/Core/Number.php
  src/Faker/Extension/Helper.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/ar_EG/Person.php
Labels: enhancement

#762 Removed legacy autoloader
  CHANGELOG.md
  phpstan-baseline.neon
  src/autoload.php
Labels: enhancement

#764 Removed the ORM integration
  CHANGELOG.md
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.baseline.xml
  roave-bc-check.yaml
  src/Faker/Guesser/Name.php
  src/Faker/ORM/CakePHP/ColumnTypeGuesser.php
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/ORM/CakePHP/Populator.php
  src/Faker/ORM/Doctrine/ColumnTypeGuesser.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Doctrine/backward-compatibility.php
  src/Faker/ORM/Mandango/ColumnTypeGuesser.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/ColumnTypeGuesser.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/ORM/Spot/ColumnTypeGuesser.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/ORM/Spot/Populator.php
  test/Faker/ORM/Doctrine/ColumnTypeGuesserTest.php
  test/Faker/ORM/Doctrine/EntityPopulatorTest.php
  test/Faker/ORM/Doctrine/PopulatorTest.php
Labels: enhancement

#768 Fix: Configure `bamarni/composer-bin-plugin`
  composer.json
Labels: bug

#753 Enhancement: Inject services
  src/Faker/Container/Container.php
  src/Faker/Container/ContainerBuilder.php
  src/Faker/Core/Barcode.php
  src/Faker/Core/Color.php
  src/Faker/Core/Coordinates.php
  src/Faker/Core/Uuid.php
  src/Faker/Core/Version.php
  test/Faker/Core/ColorTest.php
  test/Faker/Core/UuidTest.php
Labels: enhancement

#777 Fix: Declare strict types in examples
  README.md
Labels: bug

#774 Fix: Namespace
  test/Container/ContainerBuilderTest.php
  test/Container/ContainerTest.php
Labels: bug

#771 Enhancement: Allow defining services that resolve to `object` instead of `Extension`
  roave-bc-check.yaml
  src/Container/Container.php
  test/Container/ContainerTest.php
Labels: enhancement

#782 Fix: Typo
  src/Container/Container.php
Labels: bug

#783 Fix: Badge
  README.md
Labels: bug

#778 Fix: Remove scripts
  test/documentor.php
  test/test.php
Labels: bug

#785 Fix: Do not use `static` in callables
  CHANGELOG.md
  src/Faker/Provider/pt_BR/PhoneNumber.php
  test/Faker/Provider/pt_BR/PhoneNumberTest.php
Labels: bug

#786 Enhancement: Merge `1.23` into `2.0`
  CHANGELOG.md
  src/Provider/pt_BR/PhoneNumber.php
  test/Provider/pt_BR/PhoneNumberTest.php
Labels: enhancement

#787 Correct return type of `Generator::unique()`
  phpstan-baseline.neon
  psalm.baseline.xml
  src/Generator.php
Labels: bug
